"""add pop_event partitioned + pacing_bucket

Revision ID: 8a63258f9f2f
Revises: 043e976fcdac
Create Date: 2026-06-03 00:57:22.899339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a63258f9f2f'
down_revision: Union[str, Sequence[str], None] = '043e976fcdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacing_bucket',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('hour_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'hour_ts')
    )
    op.create_table('pop_event',
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('screen_id', sa.Uuid(), nullable=False),
    sa.Column('creative_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('h3_r8', sa.BigInteger(), nullable=True),
    sa.Column('h3_r9', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creative.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_ts', 'event_date', 'screen_id', 'creative_id'),
    postgresql_partition_by='RANGE (event_date)'
    )
    op.create_index('ix_pop_event_campaign_id_event_date_ts', 'pop_event', ['campaign_id', 'event_date', 'event_ts'], unique=False)
    op.create_index('ix_pop_event_screen_id_event_date', 'pop_event', ['screen_id', 'event_date'], unique=False)
    # ### end Alembic commands ###

    # Default partition catches inserts whose date range isn't covered by an
    # attached daily partition. Dev safety net; M7 (prod hardening) would
    # either DETACH this or alarm on rows landing here. See ADR-0001.
    op.execute("CREATE TABLE pop_event_default PARTITION OF pop_event DEFAULT")


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the default partition + any daily children before the parent.
    # The DEFAULT partition is named explicitly; daily children are created
    # at runtime, so this downgrade assumes any daily partitions have been
    # detached by the operator first (it's a dev migration, not a managed
    # production rollback path).
    op.execute("DROP TABLE IF EXISTS pop_event_default")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pop_event_screen_id_event_date', table_name='pop_event')
    op.drop_index('ix_pop_event_campaign_id_event_date_ts', table_name='pop_event')
    op.drop_table('pop_event')
    op.drop_table('pacing_bucket')
    # ### end Alembic commands ###
